#server
server:
  port: 80
  servlet:
    context-path: /

#spring
spring:
  datasource:
    url: jdbc:mysql://111.229.121.30:3306/jtsys?characterEncoding=utf8&serverTimezone=GMT%2B8
    password: root
    username: root
    # type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
  aop:
    proxy-target-class: false 
  # true 默认 使用继承代理
  # false 使用 组合代理(jdk代理) 
 
 
 
    
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.edut.springboot: debug   file:    path: D://temp/

#page
page: 
  config:
    pageSize: 3