server:
  port: 8081
spring:  profiles:    active:    - dev
---
spring:  profiles: 
  - dev

server:  port: 8082

#Person: 
#  lastName: 阿里
#  age: 18
#  boss: false 
#  birth: 2017/12/12 
#  maps: {k1: v1 , k2: 12}
#  list: 
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2
