#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat: 
  # tomcat 线程配置
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100

# spring
spring:
  datasource:
    url: jdbc:mysql://111.229.121.30:3306/jtsys?characterEncoding=utf8&serverTimezone=GMT%2B8
    password: root
    username: root
    # type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
  aop:
    proxy-target-class: false 
  # true 默认 使用继承代理
  # false 使用 组合代理(jdk代理) 
  task:
    execution:
      pool:
        core-size: 2 # 默认CPU核数+1
        max-size: 5 # 最大吞吐量 = max-size+queue-capacity . 超了报异常
        queue-capacity: 3 #默认100多个亿 INTEGER.MAX_VALUE
        keep-alive: 30 #30s后 释放 多余 core-size 的线程
        allow-core-thread-timeout: false #默认false 不释放core-size
      thread-name-prefix: spring.async.task- # 默认 task-
 
 
    
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.edut.springboot: debug 
  file:
    path: D://temp/

#page
page: 
  config:
    pageSize: 10

#异步线程数
async-thread-pool:
  corePoolSize: 1
  maxPoolSize: 2
  keepAliveSeconds: 30
  queueCapacity: 1
  
# webService
web-service:
  startServiceHour: 9
  endServiceHour: 17
  