#server
server:
  port: 80
  servlet:    context-path: / 

#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtsys?characterEncoding=utf8&serverTimezone=GMT%2B8
    password: root
    username: root
    # type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
    
#mybatis
mybatis:  mapper-locations: classpath:/mapper/*/*.xml

#log