#server
server:
  port: 80
  servlet:    context-path: / 

#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtsys?characterEncoding=utf8
    password: root
    username: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
    
#mybatis

#log